dataset: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv

plot_config:
  title: Iris flower analysis
  xlabel: Sepal Length
  ylabel: Sepal Width

# this is a comment
columns:
  - length
  - width
